[Definition]
failregex = ^\{.*"src_ip":\s*"<HOST>".*"event_type":\s*"alert".*\}$
            ^.*"src_ip":\s*"<HOST>".*"event_type":\s*"alert".*$

ignoreregex = 

[Init]
datepattern = ^\{.*"timestamp":\s*"%%Y-%%m-%%dT%%H:%%M:%%S\.%%f\+0000"
